module Aws
  module Sigv4
    class Credentials
      def initialize: (
        access_key_id: String,
        secret_access_key: String,
        session_token?: String?
      ) -> void

      attr_reader access_key_id: String
      attr_reader secret_access_key: String
      attr_reader session_token: String?

      def set?: () -> bool
    end

    class StaticCredentialsProvider
      def initialize: (
        credentials?: Credentials,
        access_key_id?: String,
        secret_access_key?: String,
        session_token?: String?
      ) -> void

      attr_reader credentials: Credentials

      def set?: () -> bool
    end
  end
end
